CREATE TABLE USERS(
ID INT AUTO_INCREMENT,
NAME VARCHAR(30) NOT NULL,
PASSWORD VARCHAR(8) NOT NULL,
PH_NO VARCHAR(10),
EMAIL VARCHAR(30),
PRIMARY KEY(ID));


CREATE TABLE LIBRARIAN(
LIB_ID INT AUTO_INCREMENT,
NAME VARCHAR(30) NOT NULL,
PASSWORD VARCHAR(8) NOT NULL,
PH_NO VARCHAR(10),
EMAIL VARCHAR(30),
PRIMARY KEY(LIB_ID));

CREATE TABLE BOOKS(
BOOK_ID INT AUTO_INCREMENT,
BOOK_NAME VARCHAR(50) NOT NULL,
AUTHOR VARCHAR(25) NOT NULL,
PUBLICATION_COMPANY VARCHAR(30),
STOCK INT DEFAULT 0,
PRIMARY KEY(BOOK_ID));

CREATE TABLE BOOK_USER(
BOOK_ID INT,
RENTED_USER_ID INT,
RENTED_DATE DATE,
RETURN_DATE DATE,
FEES DECIMAL,
STATUS INT DEFAULT 0,
FOREIGN KEY(BOOK_ID) REFERENCES BOOKS(BOOK_ID),
FOREIGN KEY(RENTED_USER_ID) REFERENCES USERS(ID)
);
